	<h3>Overview</h3>
	<img src="resources/mech_lg.png" class="Img" alt="" />
	<p><strong>REMLAB Web Mech Designer</strong> is a cross-platform web-based BattleMech and unit designer for the tactical board game <em>Battletech</em>. REMLAB is built entirely on HTML, PHP, and JavaScript with Ajax functionality.</p>
	<p>REMLAB requires an Apache web server (locally or remotely) with the ability to process PHP 4/5 scripts.</p>

	<h3>History</h3>
	<p>In the mid-nineties I attempted to develop my own Mech editor with <em>Visual Basic</em> after being inspired by the popular editors of the time. Around the time I started developing web sites, I realized that a HTML form based Mech editor could be possible.</p>
	<p>In late 2005 I completed the first version of REMLAB. The interface was pretty clunky and slow, but it did everything intended. The following year, I competed an improved version that included an Ajax style interface which fixed most of the clunkiness and made the program behave more like a real desktop application.</p>
	<p>Development for the current version (REMLAB 3.0) began in mid 2007.</p>

	<h3>Source Material</h3>
	<p>The official source books that I used for reference were: <em>The Compendium</em>, <em>Master Rules</em>, <em>Maximum Tech</em>, <em>Tactical Handbook</em>, <em>Solaris VII</em>, <em>BattleForce 2</em>, and <em>Total Warfare</em>. As well as <a href="http://en.wikipedia.org/wiki/Battletech">Battletech on Wikipedia</a>, <a href="http://www.sarna.net/wiki/Main_Page">Battletech Wiki</a>, and the <a href="http://www.classicbattletech.com/">official Battletech website</a>.</p>