	<h3>Introduction</h3>
	<img src="resources/mech_lg.png" class="Img" alt="" />
	<p>Welcome to <strong>REMLAB Web Mech Designer</strong>. Click on one of the unit types below to begin.</p>

	<h3>Choose a unit to build</h3>
	<div id="Units">
		<a href="mech.lab" class="Mech" title="Build a BattleMech"><span>BattleMech</span></a>
		<a href="vehicle.lab" class="Vehicle" title="Build a Combat Vehicle"><span>Combat Vehicle</span></a>
		<a href="aerotech.lab" class="Aerotech" title="Build an AeroTech Fighter"><span>AeroTech</span></a>
		<a href="protomech.lab" class="Protomech" title="Build a ProtoMech"><span>ProtoMech</span></a>
		<a href="installation.lab" class="Structure" title="Build a Structure"><span>Structure</span></a>
		<a href="dice.lab" class="Dice" title="Dice Roller"><span>Dice Roller</span></a>
	</div>
	
	<!--div id="Download"><a href="http://www.sourceforge.net/projects/remlab/">Download the source code for REMLAB<br /> from <strong>SourceForge.net</strong> &gt;&gt;</a></div-->
	
	<p style="color:#A00">This is a <strong>development</strong> version of REMLAB. So not everything you see actually works or functions properly, but should at some point.</p>