<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1" />
<title>{TITLE} {SUB_TITLE}</title>
<meta name="authors" content="{AUTHOR}" />
<meta name="description" content="A web based Battletech unit creator" />
<link type="text/css" rel="stylesheet" href="resources/remlab.css" media="screen" />
<link type="text/css" rel="stylesheet" href="resources/print.css" media="print" />
<script type="text/javascript" src="include/remlab.js"></script>
<link rel="shortcut icon" type="image/x-icon" href="favicon.ico" />
</head>

<body>

<div id="Top">
	<div id="Header" onclick="location.href='build.lab'">
		<h1>{TITLE} <span>{SUB_TITLE}</span></h1>
		<div>{VERSION}</div>
	</div>
	<div id="Navigation">
		<dl>
			<dd><a href="build.lab">Build</a></dd>
			<dd><a href="about.lab">About</a></dd>
			<dd><a href="help.lab">Help</a></dd>
		</dl>
	</div>
</div>

<div id="Content_Text">

<noscript>Javascript must be enabled for REMLAB to function.</noscript>

{PAGE_CONTENT}

</div>

<div id="Bottom">
	<div>Developed by <a href="http://www.marchtwenty.com/">March Twenty Productions</a> and distributed on <a href="http://remlab.sourceforge.net/">SourceForge.net</a>.</div>
</div>

</body>
</html>