	<h3>Printing Tips</h3>
	<img src="resources/mech_lg.png" class="Img" alt="" />
	<p>For the best results shrink the page margins as much as possible. Goto <strong>Page Setup</strong> dialog box your browser, and set the margins as low as your printer will allow, <strong>0.5&quot;</strong> is good enough. You can improve printing results by following these steps:</p>
	<ul>
		<li><em><strong>Mozilla Firefox:</strong></em><br /> Go to <strong>File &gt;&gt; Page Setup</strong>. Click on the <strong>Margins &amp; Header/Footer</strong> tab, and change all six drop-down boxes to <strong>Blank</strong>.</li>
		<li><em><strong>Internet Explorer:</strong></em><br /> Go to <strong>File &gt;&gt; Page Setup</strong>. Delete the contents of the <strong>Header</strong> and <strong>Footer</strong> text boxes. The defaults are: Header = <strong>&amp;w&amp;bPage &amp;p of &amp;P</strong> and Footer = <strong>&amp;u&amp;b&amp;d</strong></li>
		<li><em><strong>Opera:</strong></em><br /> Go to <strong>File &gt;&gt; Print options</strong>. Set the scale to <strong>90%</strong> and uncheck <strong>Print headers and footers</strong>.</li>
		<li><em><strong>Safari:</strong></em><br /> In the <strong>Print</strong> box, turn off the header and footer in one of the sub-panels.</li>
	</ul>
	<p>You may also want to turn *ON* <strong>Print Background Images</strong> to see the grey backgrounds behind the headers in the print-out, but that's up to you, it doesn't make any difference one way or the other.</p>
	
	<h3>Saving</h3>
	<p>Currently the only way to save a mech is to save the actual print-out page as an HTML file on your local computer.</p>
	<ul>
		<li><em><strong>Mozilla</strong></em>: Go to <strong>File &gt;&gt; Save Page As</strong>.</li>
		<li><em><strong>Internet Explorer</strong></em>: Go to <strong>File &gt;&gt; Save As</strong>.</li>
	</ul>
	<p>Make sure the the file name ends with <em>.html</em> or <em>.htm</em>, so your browser can view the file locally.</p>